/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

/**
 *
 * @author Gayan iz
 */
public class calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    double NumEnter1;
    double NumEnter2;
    double Result;
    String ope;
    
    
    public calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtextResult = new javax.swing.JTextField();
        jbtnCE = new javax.swing.JButton();
        jbtnBS = new javax.swing.JButton();
        jbtnplusminus = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtnplus = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtnDevide = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtnpinus = new javax.swing.JButton();
        jbtndot = new javax.swing.JButton();
        jbtnzero = new javax.swing.JButton();
        jbtnmul = new javax.swing.JButton();
        jbtnequal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtextResult.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtextResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jtextResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 340, 90));

        jbtnCE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnCE.setText("CE");
        jbtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCEActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 74, 70));

        jbtnBS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnBS.setText("BK");
        jbtnBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBSActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 74, 70));

        jbtnplusminus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnplusminus.setText("+/-");
        jbtnplusminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnplusminusActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnplusminus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 74, 70));

        jbtnC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnC.setText("C");
        getContentPane().add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 74, 70));

        jbtnplus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnplus.setText("+");
        jbtnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnplusActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnplus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 74, 70));

        jbtn9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 74, 70));

        jbtn7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 74, 70));

        jbtn8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 74, 70));

        jbtn3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 74, 70));

        jbtn2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 74, 70));

        jbtn1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 74, 70));

        jbtnDevide.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnDevide.setText("/");
        jbtnDevide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDevideActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDevide, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 74, 70));

        jbtn4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 74, 70));

        jbtn5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 74, 70));

        jbtn6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 74, 70));

        jbtnpinus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnpinus.setText("-");
        jbtnpinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpinusActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnpinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 74, 70));

        jbtndot.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtndot.setText(".");
        jbtndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndotActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndot, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 74, 70));

        jbtnzero.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnzero.setText("0");
        jbtnzero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnzeroActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnzero, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 74, 70));

        jbtnmul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnmul.setText("*");
        jbtnmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmulActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnmul, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 74, 70));

        jbtnequal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnequal.setText("=");
        jbtnequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnequalActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnequal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 74, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterNumbers(String q)
    {
        String Num = jtextResult.getText() + q;
        jtextResult.setText(Num);
         
    }
    
    
    
    
    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        EnterNumbers("1");
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        
        EnterNumbers("7");
        
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        EnterNumbers("8");
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        EnterNumbers("9");
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        EnterNumbers("4");
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        EnterNumbers("5");
        
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        EnterNumbers("6");
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        EnterNumbers("2");
        
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        EnterNumbers("3");
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtnzeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnzeroActionPerformed
        EnterNumbers("0");
    }//GEN-LAST:event_jbtnzeroActionPerformed

    private void jbtnDevideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDevideActionPerformed
        NumEnter1 = Double.parseDouble(jtextResult.getText());
        jtextResult.setText("");
        ope ="/";  
    }//GEN-LAST:event_jbtnDevideActionPerformed

    private void jbtnmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmulActionPerformed
        NumEnter1 = Double.parseDouble(jtextResult.getText());
        jtextResult.setText("");
        ope ="*";
    }//GEN-LAST:event_jbtnmulActionPerformed

    private void jbtnpinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpinusActionPerformed
        NumEnter1 = Double.parseDouble(jtextResult.getText());
        jtextResult.setText("");
        ope ="-";
    }//GEN-LAST:event_jbtnpinusActionPerformed

    private void jbtnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnplusActionPerformed
        NumEnter1 = Double.parseDouble(jtextResult.getText());
        jtextResult.setText("");
        ope ="+";
    }//GEN-LAST:event_jbtnplusActionPerformed

    private void jbtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCEActionPerformed
        jtextResult.setText("");
        
        String fun, sn;
        fun = String.valueOf(NumEnter1);
        sn = String.valueOf(NumEnter2);
        
        fun = "";
        sn  = "";
    }//GEN-LAST:event_jbtnCEActionPerformed

    private void jbtnplusminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnplusminusActionPerformed
        double nums = Double.parseDouble(String.valueOf(jtextResult.getText()));
        nums = nums * (-1);
        jtextResult.setText(String.valueOf(nums));
    }//GEN-LAST:event_jbtnplusminusActionPerformed

    private void jbtnBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBSActionPerformed
         String backspa = null;
         
         if(jtextResult.getText().length() > 0)
         {
             StringBuilder sb = new StringBuilder(jtextResult.getText());
             sb.deleteCharAt(jtextResult.getText().length()-1);
             backspa = sb.toString();
             jtextResult.setText(backspa);
         }
    }//GEN-LAST:event_jbtnBSActionPerformed

    private void jbtndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndotActionPerformed
        if (! jtextResult.getText().contains("."))
        {
            jtextResult.setText(jtextResult.getText() + jbtndot.getText());
        }
        
    }//GEN-LAST:event_jbtndotActionPerformed

    private void jbtnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnequalActionPerformed
        NumEnter2 = Double.parseDouble(jtextResult.getText());
        if(ope == "+")
        {
            Result = NumEnter1 + NumEnter2;
            jtextResult.setText(String.valueOf(Result));
        }
        
        else  if(ope == "-")
        {
            Result = NumEnter1 - NumEnter2;
            jtextResult.setText(String.valueOf(Result));
        }
        else  if(ope == "*")
        {
            Result = NumEnter1 * NumEnter2;
            jtextResult.setText(String.valueOf(Result));
        }
        else  if(ope == "/")
        {
            Result = NumEnter1 / NumEnter2;
            jtextResult.setText(String.valueOf(Result));
        }
    }//GEN-LAST:event_jbtnequalActionPerformed
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnBS;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnCE;
    private javax.swing.JButton jbtnDevide;
    private javax.swing.JButton jbtndot;
    private javax.swing.JButton jbtnequal;
    private javax.swing.JButton jbtnmul;
    private javax.swing.JButton jbtnpinus;
    private javax.swing.JButton jbtnplus;
    private javax.swing.JButton jbtnplusminus;
    private javax.swing.JButton jbtnzero;
    private javax.swing.JTextField jtextResult;
    // End of variables declaration//GEN-END:variables
}
